import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Box from "@mui/material/Box";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";

import SideBar from "@/components/SideBar/SideBar";
import { nunito } from "@/lib/fonts";
import theme from "@/lib/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box sx={{ display: "flex" }}>
              <SideBar />
              <Box
                component="main"
                sx={{ flexGrow: 1, p: 3, overflowX: "auto" }}
              >
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
